### PR TITLE
dutch translation

### PR DESCRIPTION
**Pull request by Martinusbe**

### CODE REVIEW

**Comment by hahnjo** [comment]
Would you also like to translate the description.txt and change.log for the Google Play Store?

**Comment by Martinusbe** [comment]
hi;

sure, was going to do it tomorrow

greets

2014-02-01 Jonas Hahnfeld notifications@github.com:

**Comment by hahnjo** [comment]
Ok thanks :-) just push the commits to the same branch and they will be displayed here. Will then merge it

**Comment by hahnjo** [comment]
Thanks. This pull request has been integrated manually.

**Pull request closed without merging**
