### PR TITLE
Directory selection.

### PR DESCRIPTION
**Pull request by Michael-Allan**
Added support for directory selection via Intent.ACTION_OPEN_DOCUMENT_TREE.
https://developer.android.com/about/versions/android-5.0.html#Storage

Tested build against API 22 and set manifest targetSdkVersion accordingly.

### CODE REVIEW

**Comment by hahnjo** [comment]
Thanks for your contribution!

But I won't merge in the current state:
1. There seems to be quite some refactoring. Please do this separately.
2. You can override methods and use constants from newer SDKs. You can either use `@TargetApi` (should be OK for `isChildDocument`) or surround it with an if statement:

``` Java
int flags = 0;
if (Build.VERSION.SDK_INT > Build.VERSION_CODES.LOLLIPOP) {
    flags |= DocumentsContract.Root.FLAG_SUPPORTS_IS_CHILD;
}
```
1. (Some minor code style that I would correct locally before merging: indention, for - if - return statements in one line, not importing `FileNotFoundException`)

**Comment by Michael-Allan** [comment]
You're welcome, thanks for coding the app.

Regarding item 1 (refactoring), I think the following changes are required for directory selection:

(a) Correction of index error in DocumentIdUtils.java:
https://github.com/Michael-Allan/SMBProvider/commit/49b5f68e800eabb73044cc9cbf945732c77fef68#diff-4e4340e45ee447d20e9cecb7a97aaac3R29

(b) Method isChildDocument.
https://github.com/Michael-Allan/SMBProvider/commit/49b5f68e800eabb73044cc9cbf945732c77fef68#diff-bb7849512b8c7a8fe7ac0b4071ceeb87L152

(c) FLAG_SUPPORTS_IS_CHILD
https://github.com/Michael-Allan/SMBProvider/commit/49b5f68e800eabb73044cc9cbf945732c77fef68#diff-cdc0dd6871c7d72d35a7b6321b313705R39

That leaves the following that are not strictly required for directory selection:

(i) Upgraded android:targetSdkVersion because the build has now been tested against API 22.
https://github.com/Michael-Allan/SMBProvider/commit/49b5f68e800eabb73044cc9cbf945732c77fef68#diff-a48d6def78e18cbabab3c95ae3c9fc49R8

(j) Fixed what appear to be concurrency errors in SMBProvider.java.  (m1) Deleted cursorCache because Cursor instances are not safe to share among threads.  (m2) Removed independently mutable variables lastDirectoryDocumentId and lastDirectoryDocumentList (not thread-safe) in favour of immutable ChildQueryResult.  (I should have explained this in the original commit message.)
https://github.com/Michael-Allan/SMBProvider/commit/49b5f68e800eabb73044cc9cbf945732c77fef68#diff-bb7849512b8c7a8fe7ac0b4071ceeb87L36

Should I make separate pull requests for (i) and (j)?

Mike

**Comment by Michael-Allan** [comment]
Are you still there, hahnjo?

You asked for changes.  I posted a question, but you haven't answered.

Do you want (i) and (j) removed from this pull request and requested separately?  Is that what you mean by "refactoring... do this separately"?

Mike

**Comment by hahnjo** [comment]
A huge sorry, had much to do and simply forgot to reply!

I would be ok with one merge request, but multiple commits.
If I don't miss anything, a commit for each of the following changes:
1. Index error
2. Support for child document (Could you please test simply using the new constants, guarded with an if check for the current version? Should also work for older versions as shown in my first comment)
3. Fix for the race condition

**Comment by hahnjo** [comment]
Merged #13

**Pull request closed without merging**
